services:
  sonarqube:
    image: sonarqube:community
    container_name: HarnessDemo1-sonarqube
    restart: unless-stopped
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: postgres
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs
    networks:
      - app-network

volumes:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:

networks:
  app-network:
    external: true
    name: harnessdemo1-network
