sonar.projectKey=collaborative-todo-lists
sonar.projectName=Collaborative Todo Lists

sonar.sources=src
sonar.exclusions=**/node_modules/**,src/db/migrations/**,**/*.config.*,**/*.d.ts

sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=src/coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

sonar.qualitygate.wait=true
